### ISSUE TITLE
RiseCore doesn't support 1.16.5

### ISSUE THREAD

**Issue by Hoshino2001** [promcteam/risecore#3]
RiseCore doesn't support 1.16.5
It also meaning ProMCUtilities and ProMCHousing didn't work on 1.16.5 server
Both of them need to dependencies RiseCore

**Comment by goflishMC** [comment]
Update risecore to 1.18 and make sure it works from 1.16.5 - latest version.

**Comment by AFI-Plugins** [comment]
> RiseCore doesn't support 1.16.5 It also meaning ProMCUtilities and ProMCHousing didn't work on 1.16.5 server Both of them need to dependencies RiseCore

RiseCore requires Java 16 to work. Please update your server to run with Java 16, then it should work. 

Update to 1.18.1: No update necessary as the backwards compatibility of Java allows this plugin to be run with Java 17 (required for server versions > 1.18.1)
